
version: '2'

services:
  nginx:
    image: pushkinl3/games-with-words-nginx:latest
    ports:
      - "80:80"
    links: 
      - api:api
  api:
    image: pushkinl3/games-with-words-api:latest
    ports: 
      - "3000:3000"
    command: bash start.sh
    environment:
      - NODE_ENV=production
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  worker:
    image: pushkinl3/games-with-words-worker:latest
    command: bash start.sh
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  message-queue:
    image: rabbitmq:management
    ports:
      - 5672
    ports:
      - 8080:15672
  db-worker:
    image: pushkinl3/games-with-words-db-worker:latest
    command: bash start.sh
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672     
      - DATABASE_URL=postgres://postgres:postgres@db/games-with-words-development
    links:
      - message-queue
      - db:db
      - transactiondb:transactiondb
  db:
    image: postgres:latest
    environment: 
      - "POSTGRES_DB=games-with-words-development"
      - "POSTGRES_USER=postgres"
  cron:
      image: pushkinl3/games-with-words-cron:latest
      environment:
        - AMPQ_ADDRESS=amqp://message-queue:5672
        - DATABASE_URL=postgres://postgres:postgres@db/games-with-words-development
      links:
        - message-queue
        - db:db
  transactiondb:
    image: pushkinl3/games-with-words-transactiondb:latest
    environment:
      - "POSTGRES_DB=transactions"
      - "POSTGRES_USER=postgres"