version: '2'
services:
  cron:
    image: 'gww/gww-cron:latest'
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - 'DATABASE_URL=DB_URL'
      - 'TRANSACTION_DATABASE_URL=T_DB_URL'
    links:
      - 'message-queue:message-queue'
  api-balancer:
    image: 'rancher/lb-service-haproxy:v0.4.9'
    ports:
      - '80:80/tcp'
      - '8080:8080/tcp'
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  message-queue:
    image: rabbitmq
    expose:
      - '5672'
  db-worker:
    image: 'gww/gww-db:latest'
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - 'DATABASE_URL=DB_URL'
      - 'TRANSACTION_DATABASE_URL=T_DB_URL'
      - NODE_ENV=production
    links:
      - 'message-queue:message-queue'
    command:
      - bash
      - start.sh
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: 'gww/gww-server:latest'
    links:
      - 'api:api'
    ports:
      - '80:80/tcp'
    labels:
      io.rancher.container.pull_image: always
  api:
    image: 'gww/gww-api:latest'
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - NODE_ENV=production
    links:
      - 'message-queue:message-queue'
    expose:
      - '3000'
    command:
      - bash
      - start.sh
    labels:
      io.rancher.container.pull_image: always