
version: '2'

services:
  # whichenglish:
  #   image: whichenglish:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  nginx:
    image: whichenglish-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links: 
      - api:api
  api:
    image: whichenglish-api:latest
    expose: 
      - "3000"
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
    command: bash start.debug.sh
    depends_on: 
      - "message-queue"
    environment:
      - NODE_ENV=production
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  worker:
    image: whichenglish-worker:latest
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/usr/src/app
    command: bash start.debug.sh
    depends_on: 
      - "message-queue"
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  message-queue:
    image: rabbitmq:management
    expose:
      - 5672
    ports:
      - 8080:15672