
version: '2'

services:
  nginx:
    image: games-with-words-nginx:latest
    build:
      context: ./games-with-words-nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links: 
      - api:api
  api:
    image: games-with-words-api:latest
    expose: 
      - "3000"
    build:
      context: ./games-with-words-api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
    depends_on: 
      - "message-queue"
    environment:
      - NODE_ENV=production
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  worker:
    image: games-with-words-worker:latest
    build:
      context: ./games-with-words-worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/usr/src/app
    depends_on: 
      - "message-queue"
    environment:
      - AMPQ_ADDRESS=amqp://message-queue:5672     
    links:
      - message-queue
  message-queue:
    image: rabbitmq
    expose:
      - 5672