version: '2'
services:
  cron:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        protocol: http
        service: server
        source_port: 80
        target_port: 80
      - path: /api
        protocol: http
        service: api
        source_port: 80
        target_port: 3000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  db-worker:
    scale: 1
    start_on_create: true
  server:
    scale: 1
    start_on_create: true
  api:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000
  message-queue:
    metadata:
      message-queue: *id001
    scale: 1
    start_on_create: true
  message-queue-datavolume:
    metadata:
      message-queue: &id001
        config:
          node.name: $${HOSTNAME}
    scale: 1
    start_on_create: true
  message-queue-base:
    metadata:
      message-queue: *id001
    scale: 1
    start_on_create: true
  listener-quiz:
    scale: 1
    start_on_create: true